<!--HOSPITAL WEBSITE -->
var _bg__iphone_11_pro___x___1 = document.createElement("div");
_bg__iphone_11_pro___x___1.id = "_bg__iphone_11_pro___x___1";
_bg__iphone_11_pro___x___1.style.left = "0px";
_bg__iphone_11_pro___x___1.style.top = "0px";
_bg__iphone_11_pro___x___1.style.width = "375px";
_bg__iphone_11_pro___x___1.style.height = "696px";
_bg__iphone_11_pro___x___1.style.background = 'rgba(255,255,255,1)';
 
document.body.appendChild(_bg__iphone_11_pro___x___1);

<!--HOME -->
var _bg__home = document.createElement("div");
_bg__home.id = "_bg__home";
_bg__home.style.left = "0px";
_bg__home.style.top = "0px";
_bg__home.style.width = "1366px";
_bg__home.style.height = "1857px";
_bg__home.style.background = 'rgba(252,254,254,1)';
 
document.body.appendChild(_bg__home);

<!--ABOUT US -->
var _bg__about_us = document.createElement("div");
_bg__about_us.id = "_bg__about_us";
_bg__about_us.style.left = "0px";
_bg__about_us.style.top = "0px";
_bg__about_us.style.width = "1366px";
_bg__about_us.style.height = "1857px";
_bg__about_us.style.background = 'rgba(252,254,254,1)';
 
document.body.appendChild(_bg__about_us);

<!--DOCTOR-->
var _bg__doctors = document.createElement("div");
_bg__doctors.id = "_bg__doctors";
_bg__doctors.style.left = "0px";
_bg__doctors.style.top = "0px";
_bg__doctors.style.width = "1366px";
_bg__doctors.style.height = "1870px";
_bg__doctors.style.background = 'rgba(252,254,254,1)';
 
document.body.appendChild(_bg__doctors);

<!--APPOINTMENT-->
var _bg__appointment = document.createElement("div");
_bg__appointment.id = "_bg__appointment";
_bg__appointment.style.left = "0px";
_bg__appointment.style.top = "0px";
_bg__appointment.style.width = "1366px";
_bg__appointment.style.height = "1870px";
_bg__appointment.style.background = 'rgba(252,254,254,1)';
 
document.body.appendChild(_bg__appointment);

